### ISSUE TITLE
Title Not Updated 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [surajshende247/biotree#3]
**Describe the bug**
The Title of react app is still the one that comes with create react app

**To Reproduce**
Run the App And check the title bar

**Expected behavior**
In the place of title there should be name of app `biotree`

**Screenshots**
![image](https://user-images.githubusercontent.com/76584243/135703274-60f734fc-3efb-42f7-8275-72cfdb9af0b3.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win
 - Browser [e.g. chrome, safari] mozilla
 - Version [e.g. 22] 11

**Comment by surajshende247** [comment]
@rohan-kulkarni-25 you can start working on this issue

**Comment by rohan-kulkarni-25** [comment]
Have created PR
